services:
  buttonbot:
    image: inneroot/buttonbot:latest
    pull_policy: always
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 15m
    env_file: .env
    environment:
      - bot_token=${bot_token}
      - web_app_url=${web_app_url}
      - message=${message}
      - button_title=${button_title}
      - bot_command=${bot_command}
